---
title: "county Coordinate Data"
output: html_document
date: "2024-03-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load the Libraries
```{r}
library(tidyverse)
library(ggplot2)
library(janitor)
library(shiny)
library(shinydashboard)
```

```{r}
bikes <- read_csv("datatesting/data/bicycle-fatality-and-injury-data-by-county.csv")
bikes <- clean_names(bikes) #names were upper case before
```

```{r}
county_data <- read_csv("datatesting/data/county_data.csv")
```
```{r}
county_data
```
```{r}
bikes
```

```{r}
bikes_new <- full_join(bikes, county_data)
```
```{r}
pop <- read_csv("datatesting/data/county_populations.csv")
```
```{r}
pop #found that county names do not match so asked chatgpt to fix county names
```

```{r}
updated_pop <- read_csv("datatesting/data/updated_county_populations.csv")
```
```{r}
updated_pop <- updated_pop %>%
  filter(county != "CALIFORNIA") #data has total pop which we dont need
```

```{r}
bikes_new <- full_join(bikes_new, updated_pop)
```
```{r}
bikes_new #population and year names are wrong
```

```{r}
bikes_new <- bikes_new %>%
  rename(year ="population")%>%
  rename(pop = "population.1")
```

```{r}
bikes_new
```


```{r}
# Created a data frame with the county names, latitudes, and longitudes using the help of ChatGPT
county_data <- data.frame(
  county = c("ALAMEDA", "ALPINE", "AMADOR", "BUTTE", "CALAVERAS", "COLUSA", "CONTRA COSTA", "DEL NORTE",
             "EL DORADO", "FRESNO", "GLENN", "HUMBOLDT", "IMPERIAL", "INYO", "KERN", "KINGS",
             "LAKE", "LASSEN", "LOS ANGELES", "MADERA", "MARIN", "MARIPOSA", "MENDOCINO", "MERCED",
             "MODOC", "MONO", "MONTEREY", "NAPA", "NEVADA", "ORANGE", "PLACER", "PLUMAS",
             "RIVERSIDE", "SACRAMENTO", "SAN BENITO", "SAN BERNARDINO", "SAN DIEGO", "SAN FRANCISCO",
             "SAN JOAQUIN", "SAN LUIS OBISPO", "SAN MATEO", "SANTA BARBARA", "SANTA CLARA", "SANTA CRUZ",
             "SHASTA", "SIERRA", "SISKIYOU", "SOLANO", "SONOMA", "STANISLAUS", "SUTTER", "TEHAMA",
             "TRINITY", "TULARE", "TUOLUMNE", "VENTURA", "YOLO", "YUBA"),
  latitude = c(37.6017, 38.5974, 38.3489, 39.6254, 38.196, 39.1789, 37.9191, 41.7435,
               38.7787, 36.9859, 39.5989, 40.745, 32.8397, 36.3093, 35.3433, 36.0741,
               39.1012, 40.6739, 34.0522, 36.9859, 38.0834, 37.4849, 39.5501, 37.2083,
               41.5885, 37.938, 36.2168, 38.5025, 39.1347, 33.7175, 38.9045, 40.0036,
               33.9534, 38.5816, 36.6115, 34.9592, 32.7157, 37.7749, 37.9577, 35.3102,
               37.563, 34.4208, 37.3541, 36.9741, 40.7909, 39.5774, 41.6639, 38.3105,
               38.5779, 37.5091, 39.0446, 40.1251, 40.6503, 36.1342, 37.8675, 34.3705, 38.7646, 39.2547),
  longitude = c(-121.7195, -119.8203, -120.7741, -121.537, -120.6805, -122.2342, -121.9283, -123.8974,
                -120.5231, -119.2321, -122.3935, -123.8695, -115.6121, -117.546, -118.7278, -119.8155,
                -122.7533, -120.5579, -118.2437, -120.5824, -122.7633, -119.9663, -123.4384, -120.6977,
                -120.7525, -118.8867, -121.2264, -122.2655, -121.171, -117.8311, -121.1448, -120.8393,
                -117.3962, -121.4944, -121.286, -116.4194, -117.1611, -122.4194, -121.2908, -120.4358,
                -122.3255, -119.6982, -121.9552, -122.0308, -121.8474, -120.5211, -122.545, -121.9018,
                -122.9888, -120.9876, -121.3153, -122.2345, -123.089, -118.8597, -120.2602, -119.1391, -121.9018, -121.3999)
)

# Print the data frame with county, latitude, and longitude
print(county_data) #rohan
```

```{r}
clean_names(county_data)
write.csv(county_data, "datatesting/data/county_data.csv", row.names = F) #kevin
```

#Which counties have the highest fatality rates?
```{r}
# Calculate fatality ratio
bikes_new <- bikes_new %>%
  mutate(fatality_ratio = fatality / total)

# Filter out rows with NA values in fatality_ratio
bikes_filtered <- bikes_new %>%
  filter(!is.na(fatality_ratio))

# Select the top N counties with the highest fatality ratios
top_counties <- bikes_filtered %>%
  top_n(n = 6, wt = fatality_ratio)  # Select top 6 counties; adjust "n" as needed

# Create a color palette with a unique color for each county
county_colors <- viridis::viridis(nrow(top_counties))

# Create a bar plot of fatality to crash ratios for the top N counties
ggplot(top_counties, aes(x = reorder(county, fatality_ratio), y = fatality_ratio, fill = county)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = county_colors) +  # Assign unique colors to each county
  labs(title = "Top 5 Counties with Highest Fatality to Crash Ratio",
       x = "County",
       y = "Fatality to Crash Ratio") +
  theme_minimal() +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 8))  # Adjust angle and size of x-axis labels 

```

#What is the mean fatality rate among different types of streets?
```{r}
# Filter out "One way street" and "Expressway" categories
bikes_filtered <- bikes_new %>%
  filter(highway_type != "total" & highway_type != "One-Way City Street" & highway_type != "Expressway")

# Calculate fatality rate for each type of street
fatality_rate <- bikes_filtered %>%
  mutate(fatality_rate = fatality / total * 100) %>%
  group_by(highway_type) %>%
  summarise(mean_fatality_rate = mean(fatality_rate, na.rm = TRUE))

# Define a colorful palette
color_palette <- RColorBrewer::brewer.pal(8, "Set2")  # Using the "Set3" palette with 8 colors

# Create a bar plot with enhanced aesthetics
ggplot(fatality_rate, aes(x = reorder(highway_type, mean_fatality_rate), y = mean_fatality_rate, fill = highway_type)) +
  geom_bar(stat = "identity", width = 0.6) +  # Adjusted width
  scale_fill_manual(values = color_palette) +  # Apply custom color palette
  labs(title = "Average Fatality Rate Among Types of Streets",
       x = NULL,  # Remove x-axis label
       y = "Average Fatality Rate (%)") +
  theme_minimal() +  # Minimalistic theme
  theme(
    plot.title = element_text(size = 20, hjust = 0.5, margin = margin(b = 20)),  # Larger title font size and adjusted margin
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),  # Adjusted x-axis text size, angle, and position
    axis.text.y = element_text(size = 12),  # Adjusted y-axis text size
    axis.title.y = element_text(size = 14, margin = margin(t = 0, r = 10)),  # Adjusted y-axis title size and margin
    axis.line = element_blank(),  # Remove axis lines
    panel.grid.major = element_blank(),  # Remove major gridlines
    panel.grid.minor = element_blank(),  # Remove minor gridlines
    panel.background = element_blank(),  # Remove panel background
    panel.border = element_rect(color = "black", fill = NA, size = 0.5)  # Add border around plot
  ) +
  coord_flip()  # Flip coordinates for horizontal bars

```

#How do fatality and injury rates compare among different types of streets?
```{r}
# Define UI for application
ui <- fluidPage(
  titlePanel("Bike Crashes Analysis"),
  
  sidebarLayout(
    sidebarPanel(
      selectInput("rate_type", "Select Rate Type:",
                  choices = c("fatality Rate", "injury Rate"),
                  selected = "fatality Rate")
    ),
    
    mainPanel(
      plotOutput("plot")
    )
  )
)

# Define server logic
server <- function(input, output) {
  
  # Create a boxplot
  output$plot <- renderPlot({
    # Define custom color palette
    colors <- rainbow(length(unique(bikes_new$highway_type)))
    
    if (input$rate_type == "fatality Rate") {
      data <- bikes_new %>%
        filter(highway_type != "total") %>%
        mutate(rate = fatality / total)
      
      ylab <- "fatality Rate (%)"
    } else {
      data <- bikes_new %>%
        filter(highway_type != "total") %>%
        mutate(rate = injury / total)
      
      ylab <- "injury Rate (%)"
    }
    
    ggplot(data, aes(x = reorder(highway_type, rate), y = rate, fill = highway_type)) +
      geom_boxplot(outlier.colour = "black", outlier.shape = 1, width = 0.5) +  # Use boxplot geometry with specified aesthetics for outliers
      scale_fill_manual(values = colors) +  # Apply custom color palette
      labs(title = paste(input$rate_type, "Among Types of Streets"),
           x = NULL,
           y = ylab) +
      theme_minimal() +
      theme(
        plot.title = element_text(size = 20, hjust = 0.5, margin = margin(b = 20)),
        axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 1),
        axis.text.y = element_text(size = 12),
        axis.title.y = element_text(size = 14, margin = margin(t = 0, r = 10)),
        axis.line = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, size = 0.5)
      )
  })
}

# Run the application
shinyApp(ui = ui, server = server)
```












