---
title: "Final Project"
output: html_document
date: "2024-03-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#rio is a package which reads other filetypes like xlsx and converts them to readable data in r, install_formats installs other libraries that rio is dependent on
#install.packages("rio")
#install.packages("lubridate)
#install.packages("readxl")
#install_formats()
library("rio")
library("tidyverse")
library("janitor")
library("naniar")
library("lubridate")
library("readxl")
```


```{r}
xl <- import_list("Sorghum_DATA_Final - cópia.xlsx") #returns each excel sheet as a list
xl <- clean_names(xl)
```

```{r}
xl
```


```{r}
xl_plant <- rename(xl$plant_height, "Line" = "Mutant Line") #first column for plant height is named mutant line instead of line like all others data frames
```

```{r}
xl2 <- left_join(xl_plant, xl$days_to_heading) #adds days to heading column to plant height so they appear in the same table
xl3 <- left_join(xl2, xl$panicle_weight) #adds panicle weight column to the previous table
xl3
```

```{r}
sorghum <- xl3 %>%
mutate_at("Line", str_replace, "Mutant_Sorghum_", "") #finalizes the data as sorghum by getting rid of the mutant_sorghum_ text in the line column
```

```{r}
sorghum <- clean_names(sorghum) #cleans names
```

```{r}
sorghum <- sorghum %>%
  mutate(line = as.factor(line))  #converts character class for line to factor class
```

```{r}
sorghum #this is what cleaned data looks like
```




